#pragma once
#pragma once

// From glfw3.h
#define RE_SPACE              32
#define RE_APOSTROPHE         39  
#define RE_COMMA              44  
#define RE_MINUS              45  
#define RE_PERIOD             46  
#define RE_SLASH              47  
#define RE_0                  48
#define RE_1                  49
#define RE_2                  50
#define RE_3                  51
#define RE_4                  52
#define RE_5                  53
#define RE_6                  54
#define RE_7                  55
#define RE_8                  56
#define RE_9                  57
#define RE_SEMICOLON          59  
#define RE_EQUAL              61  
#define RE_A                  65
#define RE_B                  66
#define RE_C                  67
#define RE_D                  68
#define RE_E                  69
#define RE_F                  70
#define RE_G                  71
#define RE_H                  72
#define RE_I                  73
#define RE_J                  74
#define RE_K                  75
#define RE_L                  76
#define RE_M                  77
#define RE_N                  78
#define RE_O                  79
#define RE_P                  80
#define RE_Q                  81
#define RE_R                  82
#define RE_S                  83
#define RE_T                  84
#define RE_U                  85
#define RE_V                  86
#define RE_W                  87
#define RE_X                  88
#define RE_Y                  89
#define RE_Z                  90
#define RE_LEFT_BRACKET       91  
#define RE_BACKSLASH          92  
#define RE_RIGHT_BRACKET      93  
#define RE_GRAVE_ACCENT       96  
#define RE_WORLD_1            161 US #1 */
#define RE_WORLD_2            162 US #2 */

/* Function keys */
#define RE_ESCAPE             256
#define RE_ENTER              257
#define RE_TAB                258
#define RE_BACKSPACE          259
#define RE_INSERT             260
#define RE_DELETE             261
#define RE_RIGHT              262
#define RE_LEFT               263
#define RE_DOWN               264
#define RE_UP                 265
#define RE_PAGE_UP            266
#define RE_PAGE_DOWN          267
#define RE_HOME               268
#define RE_END                269
#define RE_CAPS_LOCK          280
#define RE_SCROLL_LOCK        281
#define RE_NUM_LOCK           282
#define RE_PRINT_SCREEN       283
#define RE_PAUSE              284
#define RE_F1                 290
#define RE_F2                 291
#define RE_F3                 292
#define RE_F4                 293
#define RE_F5                 294
#define RE_F6                 295
#define RE_F7                 296
#define RE_F8                 297
#define RE_F9                 298
#define RE_F10                299
#define RE_F11                300
#define RE_F12                301
#define RE_F13                302
#define RE_F14                303
#define RE_F15                304
#define RE_F16                305
#define RE_F17                306
#define RE_F18                307
#define RE_F19                308
#define RE_F20                309
#define RE_F21                310
#define RE_F22                311
#define RE_F23                312
#define RE_F24                313
#define RE_F25                314
#define RE_KP_0               320
#define RE_KP_1               321
#define RE_KP_2               322
#define RE_KP_3               323
#define RE_KP_4               324
#define RE_KP_5               325
#define RE_KP_6               326
#define RE_KP_7               327
#define RE_KP_8               328
#define RE_KP_9               329
#define RE_KP_DECIMAL         330
#define RE_KP_DIVIDE          331
#define RE_KP_MULTIPLY        332
#define RE_KP_SUBTRACT        333
#define RE_KP_ADD             334
#define RE_KP_ENTER           335
#define RE_KP_EQUAL           336
#define RE_LEFT_SHIFT         340
#define RE_LEFT_CONTROL       341
#define RE_LEFT_ALT           342
#define RE_LEFT_SUPER         343
#define RE_RIGHT_SHIFT        344
#define RE_RIGHT_CONTROL      345
#define RE_RIGHT_ALT          346
#define RE_RIGHT_SUPER        347
#define RE_MENU               348

// Define constants for mouse buttons
#define RE_MOUSE_LEFT GLFW_MOUSE_BUTTON_LEFT
#define RE_MOUSE_RIGHT GLFW_MOUSE_BUTTON_RIGHT
